#!/usr/bin/env python

import sys
import json
import re

num_paths = len(sys.argv) - 2
out_path = sys.argv[-1]
in_paths = [
  "/Users/steve/Dropbox/Heal the Kingdom/" + arg
  for arg in sys.argv[1:-1]
]

inner_re = re.compile(r'^.*?{(.*)};.*', flags=re.MULTILINE)
rows_re = re.compile(r'{.*?}')
columns_re = re.compile(r'\d+')

datas = []

for in_path in in_paths:
  with open(in_path, 'r') as f:
    s = ' '.join(l.strip() for l in f)
    inner_s = inner_re.match(s).groups(1)[0]
    data = []
    for row in rows_re.findall(inner_s):
      data.append([int(col) for col in columns_re.findall(row)])
    datas.append(data)

with open(out_path, 'w') as f:
  json.dump({'layers': datas}, f)